runtime: nodejs18
env: flex
entrypoint: npm start

# Default Environment Variables
env_variables:
  NODE_ENV: production
  API_KEY: "98a2c61bc3d840c9853a8d1754607bd3"

# Instance Configuration
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Network Configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 2
